import { setupTheme }         from './features/theme';
import { setupUndoRedo }      from './features/undo-redo';
import { setupZoom }           from './features/zoom';
import { setupAutoFit }        from './features/auto-fit';
import { setupProfile }        from './features/profile';
import { setupSelectCopy }     from './features/select-copy';
import { setupDelimiterBadge } from './features/delimiter';
import { setupExport }         from './features/export';
import { setupFreezeColumns }  from './features/freeze-columns';
import { setupDeleteRowCol }   from './features/delete-row-col';
import { setupFindReplace }    from './features/find-replace';
import { setupPagination }     from './features/pagination';
import { setupGoToRow }        from './features/go-to-row';
import { setupDuplicates }     from './features/duplicates';
import { setupKeyboard }       from './keyboard';
import { setupMessaging }      from './messaging';

setupTheme();
setupUndoRedo();
setupZoom();
setupAutoFit();
setupProfile();
setupSelectCopy();
setupDelimiterBadge();
setupExport();
setupFreezeColumns();
setupDeleteRowCol();
setupFindReplace();
setupPagination();
setupGoToRow();
setupDuplicates();
setupKeyboard();
setupMessaging();

vscodeApi.postMessage({ type: 'ready' });
